# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b44feb77d9f83238db1d30a24d117ae27ce557bc4773f35fa04cf8f1088d7055751279217643353bdb9f91062e3b2d6a7889babbcacbcba78918760f655eb1e

test:
  secret_key_base: d84a3220db571837c4fa30e6945f02735428bfb2962e5300b69d1a8d195ec9c60dbf0d058c48de85c359386f7b88c3ad9d79209874c6ea2833b5cbc5627e0693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
